<a href="https://colab.research.google.com/github/SamanthaGoldhammer/FTI_Project1/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Global AI Content Impact

In [2]:
import pandas as pd

In [3]:
url = "https://raw.githubusercontent.com/frontiertechinstitute/datasets/refs/heads/main/AI%20and%20Digital%20Media/Global_AI_Content_Impact_Dataset.csv"
df = pd.read_csv(url)
df.head()

,Country,Year,Industry,AI Adoption Rate (%),AI-Generated Content Volume (TBs per year),Job Loss Due to AI (%),Revenue Increase Due to AI (%),Human-AI Collaboration Rate (%),Top AI Tools Used,Regulation Status,Consumer Trust in AI (%),Market Share of AI Companies (%)
0,South Korea,2022,Media,44.29,33.09,16.77,46.12,74.79,Bard,Strict,40.77,18.73
1,China,2025,Legal,34.75,66.74,46.89,52.46,26.17,DALL-E,Strict,35.67,35.02
2,USA,2022,Automotive,81.06,96.13,10.66,45.60,39.66,Stable Diffusion,Moderate,54.47,22.76
3,France,2021,Legal,85.24,93.76,27.70,78.24,29.45,Claude,Moderate,51.84,1.93
4,France,2021,Gaming,78.95,45.62,17.45,1.05,21.70,Midjourney,Strict,41.77,21.41

In [4]:
df.columns=(df.columns.str.strip())
df.columns=(df.columns.str.lower())
df.columns

Index(['country', 'year', 'industry', 'ai adoption rate (%)',
       'ai-generated content volume (tbs per year)', 'job loss due to ai (%)',
       'revenue increase due to ai (%)', 'human-ai collaboration rate (%)',
       'top ai tools used', 'regulation status', 'consumer trust in ai (%)',
       'market share of ai companies (%)'],
      dtype='object')

In [5]:
df.isnull().sum()

country                                       0
year                                          0
industry                                      0
ai adoption rate (%)                          0
ai-generated content volume (tbs per year)    0
job loss due to ai (%)                        0
revenue increase due to ai (%)                0
human-ai collaboration rate (%)               0
top ai tools used                             0
regulation status                             0
consumer trust in ai (%)                      0
market share of ai companies (%)              0
dtype: int64

In [6]:
df.shape

(200, 12)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   country                                     200 non-null    object
 1   year                                        200 non-null    int64
 2   industry                                    200 non-null    object
 3   ai adoption rate (%)                        200 non-null    float64
 4   ai-generated content volume (tbs per year)  200 non-null    float64
 5   job loss due to ai (%)                      200 non-null    float64
 6   revenue increase due to ai (%)              200 non-null    float64
 7   human-ai collaboration rate (%)             200 non-null    float64
 8   top ai tools used                           200 non-null    object
 9   regulation status                           200 non-null    object
 10  consumer trust in ai (%)                    200 non-null    float64
 11  market share of ai companies (%)            200 non-null    float64
dtypes: float64(7), int64(1), object(4)
memory usage: 18.9+ KB

In [8]:
print(df.duplicated().sum())

0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   country                                     200 non-null    object
 1   year                                        200 non-null    int64
 2   industry                                    200 non-null    object
 3   ai adoption rate (%)                        200 non-null    float64
 4   ai-generated content volume (tbs per year)  200 non-null    float64
 5   job loss due to ai (%)                      200 non-null    float64
 6   revenue increase due to ai (%)              200 non-null    float64
 7   human-ai collaboration rate (%)             200 non-null    float64
 8   top ai tools used                           200 non-null    object
 9   regulation status                           200 non-null    object
 10  consumer trust in ai (%)                    200 non-null    float64
 11  market share of ai companies (%)            200 non-null    float64
dtypes: float64(7), int64(1), object(4)
memory usage: 18.9+ KB

In [10]:
df.head()

,country,year,industry,ai adoption rate (%),ai-generated content volume (tbs per year),job loss due to ai (%),revenue increase due to ai (%),human-ai collaboration rate (%),top ai tools used,regulation status,consumer trust in ai (%),market share of ai companies (%)
0,South Korea,2022,Media,44.29,33.09,16.77,46.12,74.79,Bard,Strict,40.77,18.73
1,China,2025,Legal,34.75,66.74,46.89,52.46,26.17,DALL-E,Strict,35.67,35.02
2,USA,2022,Automotive,81.06,96.13,10.66,45.60,39.66,Stable Diffusion,Moderate,54.47,22.76
3,France,2021,Legal,85.24,93.76,27.70,78.24,29.45,Claude,Moderate,51.84,1.93
4,France,2021,Gaming,78.95,45.62,17.45,1.05,21.70,Midjourney,Strict,41.77,21.41

In [11]:
df["country"]=df["country"].replace({"USA":"United States of America"})

In [12]:
df["country"]=df["country"].replace({"UK":"United Kingdom"})

In [13]:
df.head()

,country,year,industry,ai adoption rate (%),ai-generated content volume (tbs per year),job loss due to ai (%),revenue increase due to ai (%),human-ai collaboration rate (%),top ai tools used,regulation status,consumer trust in ai (%),market share of ai companies (%)
0,South Korea,2022,Media,44.29,33.09,16.77,46.12,74.79,Bard,Strict,40.77,18.73
1,China,2025,Legal,34.75,66.74,46.89,52.46,26.17,DALL-E,Strict,35.67,35.02
2,United States of America,2022,Automotive,81.06,96.13,10.66,45.60,39.66,Stable Diffusion,Moderate,54.47,22.76
3,France,2021,Legal,85.24,93.76,27.70,78.24,29.45,Claude,Moderate,51.84,1.93
4,France,2021,Gaming,78.95,45.62,17.45,1.05,21.70,Midjourney,Strict,41.77,21.41

In [14]:
automotive_industry = df[df['industry'] == 'Automotive']
print(automotive_industry[['country', 'revenue increase due to ai (%)','year']])

                      country  revenue increase due to ai (%)  year
2    United States of America                           45.60  2022
25                     France                           44.06  2020
31                      India                           23.50  2022
51                South Korea                           60.61  2020
69                  Australia                           76.76  2024
82             United Kingdom                           51.87  2022
92                      China                           75.69  2022
100                     Japan                           25.17  2025
124                 Australia                           36.05  2020
132            United Kingdom                            5.14  2022
144            United Kingdom                           64.98  2021
147                     India                           53.59  2020
150                    France                           43.32  2024
157            United Kingdom                           28.93  2024
161            United Kingdom                           57.91  2020
174                    Canada                           50.61  2022
186                     India                           76.74  2020
195                   Germany                           12.14  2021
198                 Australia                           50.50  2023

In [15]:
marketshareunder20 = df[df['market share of ai companies (%)'] < 20]
print(marketshareunder20[['country', 'revenue increase due to ai (%)', 'market share of ai companies (%)','year']])

                      country  revenue increase due to ai (%)  \
0                 South Korea                           46.12
3                      France                           78.24
5    United States of America                           27.58
6                   Australia                           53.13
14   United States of America                           12.41
..                        ...                             ...
183                     India                           60.81
184                   Germany                           62.27
188            United Kingdom                           14.76
193               South Korea                            7.11
197                    France                           79.44

     market share of ai companies (%)  year
0                               18.73  2022
3                                1.93  2021
5                                8.09  2021
6                               15.26  2023
14                               5.76  2025
..                                ...   ...
183                             14.06  2024
184                             12.95  2021
188                             12.56  2022
193                             11.61  2025
197                             14.62  2023

[66 rows x 4 columns]

In [17]:
print(df["country"].unique())

['South Korea' 'China' 'United States of America' 'France' 'Australia'
 'United Kingdom' 'Canada' 'India' 'Japan' 'Germany']